name: Deploy

on: [pull_request]

env:
  GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}

jobs:
  build:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "smart-sauna-map-back"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
